#!/bin/bash
# tests/test-precompact-hook.sh — Tests for the PreCompact kill hook
#
# Tests:
#   PC1: Mini-dehydration generated when DEHYDRATED_CONTEXT.md missing
#   PC2: Existing DEHYDRATED_CONTEXT.md preserved (not overwritten)
#   PC3: Session marked as restarting via session.sh restart
#   PC4: No-ops when no session is active
#   PC5: Manual compaction (matcher=manual) exits immediately
#
# Run: bash ~/.claude/engine/scripts/tests/test-precompact-hook.sh

set -uo pipefail
source "$(dirname "$0")/test-helpers.sh"

# Capture real paths before fake home
REAL_SCRIPTS_DIR="$HOME/.claude/scripts"
REAL_ENGINE_DIR="$HOME/.claude/engine"

TMP_DIR=$(mktemp -d)
export CLAUDE_SUPERVISOR_PID=$$

setup_fake_home "$TMP_DIR"
disable_fleet_tmux

# Create engine dirs in fake home
mkdir -p "$FAKE_HOME/.claude/engine/hooks"
mkdir -p "$FAKE_HOME/.claude/engine/scripts"

# Symlink core scripts
ln -sf "$REAL_ENGINE_DIR/scripts/session.sh" "$FAKE_HOME/.claude/scripts/session.sh"
ln -sf "$REAL_SCRIPTS_DIR/lib.sh" "$FAKE_HOME/.claude/scripts/lib.sh"
ln -sf "$REAL_ENGINE_DIR/hooks/pre-compact-kill.sh" "$FAKE_HOME/.claude/engine/hooks/pre-compact-kill.sh"
ln -sf "$REAL_ENGINE_DIR/config.sh" "$FAKE_HOME/.claude/engine/config.sh" 2>/dev/null || true

# Stub fleet and search tools
mock_fleet_sh "$FAKE_HOME"
mock_search_tools "$FAKE_HOME"

# Work in TMP_DIR
cd "$TMP_DIR"

# Test session
TEST_SESSION="$TMP_DIR/sessions/test_precompact"
mkdir -p "$TEST_SESSION"

HOOK="$FAKE_HOME/.claude/engine/hooks/pre-compact-kill.sh"

cleanup() {
  teardown_fake_home
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

# Helper: create an active session state
create_active_state() {
  cat > "$TEST_SESSION/.state.json" <<STATEEOF
{
  "activePid": $$,
  "pid": $$,
  "skill": "implement",
  "lifecycle": "active",
  "currentPhase": "4: Build Loop",
  "taskSummary": "Test task for PreCompact",
  "contextUsage": 0.90,
  "toolCallsByTranscript": {},
  "toolCallsSinceLastLog": 0
}
STATEEOF
}

# Helper: run hook in TEST_MODE
run_precompact() {
  local event="${1:-auto}"
  local input
  input=$(jq -n --arg e "$event" '{event: $e}')
  echo "$input" | TEST_MODE=1 bash "$HOOK" 2>/dev/null
}

echo "======================================"
echo "PreCompact Hook Tests"
echo "======================================"
echo ""

# PC1: Mini-dehydration generated when DEHYDRATED_CONTEXT.md missing
echo "--- PC1: Mini-dehydration generation ---"
create_active_state

# Create a dummy log file so artifact listing has content
echo "# Implementation Log" > "$TEST_SESSION/IMPLEMENTATION_LOG.md"

# Ensure no existing dehydration
rm -f "$TEST_SESSION/DEHYDRATED_CONTEXT.md"

OUT=$(run_precompact "auto")
assert_file_exists "$TEST_SESSION/DEHYDRATED_CONTEXT.md" "PC1a: DEHYDRATED_CONTEXT.md created"

CONTENT=$(cat "$TEST_SESSION/DEHYDRATED_CONTEXT.md")
assert_contains "Auto-Generated by PreCompact Hook" "$CONTENT" "PC1b: Contains auto-generated marker"
assert_contains "Test task for PreCompact" "$CONTENT" "PC1c: Contains taskSummary"
assert_contains "4: Build Loop" "$CONTENT" "PC1d: Contains currentPhase"
assert_contains "IMPLEMENTATION_LOG.md" "$CONTENT" "PC1e: Lists session artifacts"

echo ""

# PC2: Existing DEHYDRATED_CONTEXT.md preserved
echo "--- PC2: Existing dehydration preserved ---"
create_active_state

# Create pre-existing dehydration with marker content
echo "# Existing dehydration — DO NOT OVERWRITE" > "$TEST_SESSION/DEHYDRATED_CONTEXT.md"

OUT=$(run_precompact "auto")
CONTENT=$(cat "$TEST_SESSION/DEHYDRATED_CONTEXT.md")
assert_contains "DO NOT OVERWRITE" "$CONTENT" "PC2: Existing DEHYDRATED_CONTEXT.md not overwritten"

echo ""

# PC3: TEST_MODE reports would-call session.sh restart
echo "--- PC3: Session restart delegation ---"
create_active_state
rm -f "$TEST_SESSION/DEHYDRATED_CONTEXT.md"

OUT=$(run_precompact "auto")
assert_contains "Would call session.sh restart" "$OUT" "PC3a: TEST_MODE reports restart intent"
assert_contains "$TEST_SESSION" "$OUT" "PC3b: Reports correct session directory"

echo ""

# PC4: No-ops when no session is active
echo "--- PC4: No-op without session ---"
# Remove the test session state to simulate no session
rm -f "$TEST_SESSION/.state.json"

OUT=$(run_precompact "auto")
assert_contains "No active session" "$OUT" "PC4: No-ops gracefully when no session found"

# Restore for next tests
create_active_state

echo ""

# PC5: Manual compaction exits immediately
echo "--- PC5: Manual compaction ignored ---"
create_active_state
rm -f "$TEST_SESSION/DEHYDRATED_CONTEXT.md"

OUT=$(run_precompact "manual")
assert_file_not_exists "$TEST_SESSION/DEHYDRATED_CONTEXT.md" "PC5: Manual compaction does not trigger hook (no dehydration created)"

echo ""

# ============================================================
# Results
# ============================================================
exit_with_results
